name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1 Get code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3 Build Docker image
      - name: Build Docker image
        run: docker build -t medical-chatbot .

      # 4 Run container (smoke test)
      - name: Run container
        run: |
          docker run -d -p 8080:8080 medical-chatbot
          sleep 10
